#+TITLE: Guidelines for realization of VLEAD SSAD projects.
#+AUTHOR: VLEAD
#+DATE: [2017-08-11 Fri]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Repository for the realization
  Each project is realized as one or more repositories under
  [[https://github.com/vlead/][vlead]] organization.  Each team will follow
  [[https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#wfdiag_b][integration-manager]] workflow.  The team will work on a
  forked repository and the mentor will merge to the blessed
  repository upon pull requests.  This way, the mentor is
  forced to review the realization documents.  If SSAD
  course mandates it's own repo, please refer to the vlead
  repo in the readme of the ssad repo. 

* Realization is in terms of milestones.
  We will follow [[agile]] software development and use [[https://www.scrumalliance.org/why-scrum][scrum]]
  methodology to incrementally working software.  Every
  project has a product backlog.  In each sprint, items from
  the product backlog are picked to be realized in a
  milestone.  Each item from a product backlog translates to
  one or more tasks and each task is tracked as an issue on
  github.  A milestone is a collection of issues.  It is
  upto the mentor and the team to choose either one or two
  week sprints.

  Each release is working software and a release determines
  the achievement of a milestone.  A project is realized as
  a series of milestones.

  This planning will be part of the master repo in the vlead
  organization. 

* Discussion is only through issues.
  Every discussion about the project will be through
  issues.  Mails are not used for discussion.

* Total person hours
  40 hours, I will find out from Prof. Raghu.

* Development Environment
  Literate style is used for the realization of projects.
  Emacs and Org are are equipped to support literate
  programming.  

  VLEAD has published a [[http://files.vlabs.ac.in/downloads/vagrant-boxes/vlead-dev.box][vagrant box]] to support the
  development environment at VLEAD.  Please follow the
  [[https://github.com/vlead/vlead-onboarding/blob/master/src/set-up-vlead-dev-vagrant-box.org][documentation]] to set up the vlead dev environment as a
  vagrant box. 

* Things done at the weekly meeting
  1. Every meeting starts with a presentation of the code
     documents and a demonstration.
  2. The pull/merge request is reviewed at the meeting.
  3. Task planning for the next week is discussed.  The
     students take the meeting notes.  The meeting notes has
     the following structure.  From the meeting, action
     items are thrashed out and are listed.  This file is
     also part of the repository.  This file ==meeting.org=
     is placed under src/realization-plan directory.

     #+BEGIN_EXAMPLE
     * [2017-09-01 Fri]
     ** Agenda
     ** Discussion Points
     ** Action
     |------------------+---------+--------------+-------------+---|
     | Item             | Issue   | Artifact     | Status      |   |
     |------------------+---------+--------------+-------------+---|
     | Implement filter | Link to | link to file | In progress |   |
     |                  | issue   | in the repo  |             |   |
     |------------------+---------+--------------+-------------+---|

     #+END_EXAMPLE

* Structure of the repository
  
  #+BEGIN_EXAMPLE
  |--makefile
  |--init.sh
  |--.gitignore
  |--src
      \-- index.org
      \-- requirements
      \-- data-model
      \-- design
      \-- runtime
      \-- realization-plan
      \-- deployment
  #+END_EXAMPLE

  - requirements are captured in index.org file in =requirements= directory.
  - same with all other artifacts.
  - code that runs goes into various documents in runtime
    directory.
  - realization plan will capture the requirements to
    milestones and issues mapping. 
  
  Please look at [[https://gitlab.com/itws2/web-app-short-course][web-app-short-course]] for reference.

* Work logs
  The work logs of each student are pushed to this
  repository to the =work-logs= folder. 
    




